name: shoplist
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  get_it: ^7.6.7
  google_fonts: ^6.1.0
  lottie: ^3.0.0
  material_symbols_icons: ^4.2719.1
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    # - assets/images/
